apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
# Install Strimzi Operator (Helm alternative: helm repo add strimzi ...)
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: strimzi-cluster-operator
    namespace: operators
  data: {}
