apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: parallelservicesllc-com-wildcard
  namespace: istio-system
spec:
  secretName: parallelservicesllc-com-wildcard-tls
  duration: 90d
  renewBefore: 15d
  dnsNames:
  - "parallelservicesllc.com"
  - "*.parallelservicesllc.com"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
