apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: payment-service
        image: aiinfraacr2901.azurecr.io/payment-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: payments_user.payments-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payments_user.payments-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: payments_user.payments-db.credentials.postgresql.acid.zalan.do
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: payments_user.payments-db.credentials.postgresql.acid.zalan.do
              key: port
