apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: aiinfraacr2901.azurecr.io/payment-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: payments-user.payments-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payments-user.payments-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DB_HOST
          value: payments-db.postgres.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: paymentsdb
