apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: aiinfraacr2901.azurecr.io/payment-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: payments-db-payments_user.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payments-db-payments_user.credentials.postgresql.acid.zalan.do
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: payments-db-payments_user.credentials.postgresql.acid.zalan.do
              key: dbname
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: payments-db-payments_user.credentials.postgresql.acid.zalan.do
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: payments-db-payments_user.credentials.postgresql.acid.zalan.do
              key: port
