apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: aiinfraacr2901.azurecr.io/payment-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: payments-db-credentials
